name: build-main
run-name: build-main
on:
  push:
    branches:
      - main
  schedule:
    # every hour
    - cron: 0 * * * *

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: fetch data and create stats
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4

      - run: pip install astral duckdb

      - run: python3 main.py

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5 